---
logstash_forwarder_config_dir: '/etc/logstash-forwarder/conf.d'
logstash_forwarder_split_files: true
logstash_forwarder_servers:
logstash_forwarder_ssl_cert:
logstash_forwarder_ssl_key:
logstash_forwarder_ssl_ca:
logstash_forwarder_files:
logstash_forwarder_log_to_syslog: true
logstash_forwarder_cpuprofile: ''
logstash_forwarder_spool_size: 1024
logstash_forwarder_idle_flush_time': ''
logstash_forwarder_from_beginning: false
logstash_forwarder_start: false
logstash_forwarder_enabled: true
